idf_component_register(SRCS 
                        "main.cpp"
                        "matrix/hub75_driver.cpp"
                        "esp/espio.c"
                        "engine/ctetris.c"
                        "engine/renderer.cpp"
                        "engine/lerp.c"
                        "events/edt.cpp"
                        "assets/assets.c"
                        "tft/tft.cpp"
                        "tft/adafruit/Adafruit_GFX.cpp"
                       INCLUDE_DIRS 
                        "."
                        "matrix/"
                        "esp/"
                        "engine/"
                        "events/"
                        "assets/"
                        "audio/"
                        "tft/"
                        "tft/adafruit"
                       REQUIRES 
                        driver 
                        esp_lcd)
